(() => {
'use strict';
const $ = s => document.querySelector(s);
const KEY = 'interspace-platform-v1';
const characters = [
 {id:'bruce',name:'Bruce',initial:'B',source:'official',sourceLabel:'官方示例',tag:'好奇心',theme:'companion',tone:'#e2e8d9',subtitle:'从月球来到地球的好奇观察者',quote:'如果你能去地球上的任何地方，你会选哪里？',bio:'住在伦敦，喜欢研究人类文化。好奇、爱玩，偶尔带一点讽刺；比起标准答案，他更想知道你为什么这样想。',world:'来自月球，正在适应地球生活。这是现有团队测试角色的展示入口。',live:true},
 {id:'night',name:'未眠',initial:'夜',source:'official',sourceLabel:'官方概念',tag:'深夜电台',theme:'night',tone:'#e0e4eb',subtitle:'守着午夜频率的电台主持人',quote:'这一首播完，还想再坐一会儿吗？',bio:'安静但不敷衍，习惯听人把话说完。这里先展示角色卡的内容结构。',world:'一座没有固定日落时间的城市，一间仍然亮灯的广播室。',live:false},
 {id:'orbit',name:'偏航',initial:'↗',source:'creator',sourceLabel:'创作者示例 · 非真实上架',tag:'不靠谱搭档',theme:'companion',tone:'#ece3d7',subtitle:'方向感欠佳的星际快递员',quote:'好消息，我们到了。坏消息，不是这里。',bio:'热心、乐观，总有新的办法。用于预览创作者角色的展示方式，暂无真实作者或交易。',world:'一条不断偏离目的地的星际配送路线。',live:false}
];
let state = {favorites:[],drafts:[],guideHidden:false};
try {const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s && typeof s==='object'){state.favorites=Array.isArray(s.favorites)?s.favorites.filter(id=>characters.some(c=>c.id===id)):[];state.drafts=Array.isArray(s.drafts)?s.drafts.filter(d=>d && typeof d.id==='string' && typeof d.name==='string').map(d=>Object.fromEntries(['id','name','identity','personality','world','relationship','opening'].map(k=>[k,typeof d[k]==='string'?d[k]:'']))):[];state.guideHidden=s.guideHidden===true;}}catch{}
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('浏览器未能保存，请导出草稿备份；本次修改仍在当前页面中。');return false;}}
const portrait = c => `<div class="portrait" style="--tone:${c.tone||'#e2e8d9'}"><span>${esc(c.initial||c.name.slice(0,1)||'OC')}</span></div>`;
const button = (text,href,primary=false) => `<a class="button${primary?' primary':''}" href="${href}">${text}</a>`;
function card(c){return `<article class="card"><a href="#/character/${c.id}" aria-label="查看 ${esc(c.name)}">${portrait(c)}</a><div class="card-body"><div class="card-top"><h3><a href="#/character/${c.id}">${esc(c.name)}</a></h3><span class="tag${c.live?' live':''}">${c.live?'可试聊':'概念占位'}</span></div><span class="tag">${c.tag}</span><p>“${esc(c.quote)}”</p><div class="card-bottom"><small>${c.sourceLabel}</small><button class="favorite" data-favorite="${c.id}" aria-label="${state.favorites.includes(c.id)?'取消收藏':'收藏'} ${c.name}" aria-pressed="${state.favorites.includes(c.id)}">${state.favorites.includes(c.id)?'♥':'♡'}</button></div></div></article>`;}
const head=(over,title,copy)=>`<div class="page-head"><div class="eyebrow">${over}</div><h1>${title}</h1><p class="intro">${copy}</p></div>`;
function home(){let recent=false;try{recent=JSON.parse(localStorage.getItem('littlemind-bruce-local-chat-v1')||'[]').length>0;}catch{}return `<section class="hero"><div><div class="eyebrow">A meeting point between worlds</div><h1>在世界的间隙，<br>遇见另一种可能。</h1><p class="intro">有些相遇，来自想象。<br>发现一个有趣的角色，或者让你心中的那个人，<br>从这里开始拥有自己的故事。</p><div class="actions"><button class="button primary" data-encounter>随便遇见一个 <span>↗</span></button>${button('浏览角色广场','#/explore')}</div><a class="text-link" href="#/studio">我想创造自己的 OC →</a></div><div class="hero-art" aria-hidden="true"><span class="art-label">INTERSPACE / 001<br>一切，也是一无所有。</span></div></section>
<section class="section"><div class="section-heading"><div class="eyebrow">${recent?'CONTINUE YOUR STORY':'FIRST CONTACT'}</div><small>第一位可体验角色</small></div><div class="feature">${portrait(characters[0])}<div><span class="tag live">Bruce · 官方示例</span><h3>${recent?'你的故事，还可以继续。':'从一个问题，认识 Bruce。'}</h3><p class="muted">“${characters[0].quote}”</p><small>已有聊天接入 · 对话保存在当前浏览器</small></div>${button(recent?'继续对话 ↗':'和他聊聊 ↗','/static/bruce.html',true)}</div></section>
<section class="section"><div class="section-heading"><div><div class="eyebrow">CHARACTER DIRECTORY</div><h2>来自不同世界的面孔</h2></div><a class="text-link" href="#/explore">查看全部 ↗</a></div><div class="cards">${characters.map(card).join('')}</div></section>
<section class="section"><div class="section-heading"><div><div class="eyebrow">SMALL DETOURS</div><h2>今天，想遇见什么样的人？</h2></div></div><div class="themes"><a class="theme" href="#/explore?theme=night"><div><h3>深夜还没睡的人</h3><p>给没说完的话，留一点时间。</p></div><span>↗</span></a><a class="theme" href="#/explore?theme=companion"><div><h3>不按计划走的搭档</h3><p>也许，绕路才是故事的开始。</p></div><span>↗</span></a></div></section>`;}
function explore(params){return `${head('EXPLORE / 角色广场','故事很多，从谁开始？','按性格寻找，也可以让一次偶遇替你决定。概念角色仅展示设定，暂未接入聊天。')}<div class="toolbar"><input id="search" type="search" maxlength="100" placeholder="搜索名字、性格或一句台词" aria-label="搜索角色" value="${esc(params.get('q')||'')}"><select id="source" aria-label="角色来源"><option value="all">全部来源</option><option value="official">官方角色</option><option value="creator">创作者角色</option></select><select id="theme" aria-label="主题"><option value="all">全部主题</option><option value="night">深夜还没睡的人</option><option value="companion">不按计划走的搭档</option></select><button class="button" data-encounter>随机相遇 ↗</button></div><p id="result-count" class="muted" aria-live="polite"></p><div id="results" class="cards"></div>`;}
function filterResults(){const q=$('#search').value.toLowerCase();const source=$('#source').value;const theme=$('#theme').value;const cs=characters.filter(c=>(source==='all'||c.source===source)&&(theme==='all'||c.theme===theme)&&[c.name,c.tag,c.quote,c.bio].join(' ').toLowerCase().includes(q));$('#result-count').textContent=`${cs.length} 位角色 · 只有标注“可试聊”的角色已接入对话`;$('#results').innerHTML=cs.length?cs.map(card).join(''):`<div class="empty"><h3>还没有遇到匹配的角色</h3><p>试试别的关键词，或者清除筛选。</p><a class="button" href="#/explore">清除筛选</a></div>`;const params=new URLSearchParams();if(q)params.set('q',$('#search').value);if(source!=='all')params.set('source',source);if(theme!=='all')params.set('theme',theme);history.replaceState(null,'',`#/explore${params.size?'?'+params:''}`);}
function detail(c){if(!c)return missing();return `<a class="back" href="#/explore">← 返回角色广场</a><div class="detail-grid">${portrait(c)}<section class="detail-copy"><div class="eyebrow">CHARACTER FILE / ${c.id.toUpperCase()}</div><h1>${c.name}</h1><p class="intro">${c.subtitle}</p><span class="tag">${c.sourceLabel}</span><span class="tag${c.live?' live':''}">${c.live?'可试聊':'概念占位'}</span><div class="panel"><h3>“${c.quote}”</h3><p class="muted">${c.bio}</p></div><div class="actions">${c.live?button('进入对话 ↗','/static/bruce.html',true):'<button class="button" data-unavailable="这个角色目前仅供浏览设定，暂未接入模型。">试聊尚未开放</button>'}<button class="button" data-favorite="${c.id}">${state.favorites.includes(c.id)?'已收藏 ♥':'收藏角色 ♡'}</button></div><p class="muted">${c.live?'试聊使用原有团队访问码。聊天记录与手动记忆保留在此浏览器。':'这是一份展示结构的示例，尚未作为商品上架。'}</p></section></div><section class="section settings"><div class="panel"><h3>他所在的世界</h3><p>${c.world}</p></div><div class="panel"><h3>展示与授权</h3><p>当前仅供平台原型体验，不提供角色购买或商业使用授权。未来会在这里列出作者、许可范围、价格与交付内容。</p><button class="text-link" data-unavailable="交易系统尚未接入，目前不会产生订单或扣款。">了解购买状态 ↗</button></div></section>`;}
function mine(tab='recent'){return `${head('YOUR CORNER / 我的角色','把相遇，留在这里。','继续对话、收好喜欢的角色，或回到你正在创作的故事。收藏与草稿仅保存在当前浏览器。')}<div class="tabs" aria-label="角色分类">${[['recent','最近对话'],['favorites','我的收藏'],['drafts','我的创作'],['owned','已获得']].map(([id,n])=>`<button data-mine="${id}" class="${tab===id?'active':''}" aria-pressed="${tab===id}">${n}</button>`).join('')}</div>${tab==='recent'?`<div class="feature">${portrait(characters[0])}<div><h3>Bruce</h3><p class="muted">从原来的测试页继续，或开始第一次对话。</p><a class="text-link" href="#/space/bruce">进入私人角色空间 ↗</a></div>${button('进入对话 ↗','/static/bruce.html',true)}</div>`:tab==='favorites'?`<div class="cards">${characters.filter(c=>state.favorites.includes(c.id)).map(card).join('')}</div>${state.favorites.length?'':empty('还没有收藏的角色','在广场点击爱心，把想再见的人留在这里。','去逛逛','#/explore')}`:tab==='drafts'?`${state.drafts.map(d=>`<div class="panel draft-row"><div><span class="tag">私有草稿 · 本机</span><h3>${esc(d.name)}</h3><p class="muted">${esc(d.identity||'还没有填写身份')}</p></div><div class="actions">${button('继续编辑',`#/studio/${encodeURIComponent(d.id)}`)}<button class="text-link" data-delete="${esc(d.id)}">删除</button></div></div>`).join('')}${button('创建新角色 +','#/studio',true)}`:empty('这里将存放你获得的角色','购买和授权系统尚未开放，目前没有订单或已购角色。','浏览角色','#/explore')}`;}
function empty(title,copy,label,href){return `<div class="empty"><h3>${title}</h3><p>${copy}</p>${button(label,href)}</div>`;}
function space(){return `${head('PRIVATE SPACE / 角色空间','Bruce，与你的故事。','这是私人空间的结构预览。实际聊天和手动记忆仍在原有对话页中管理。')}<div class="actions">${button('继续对话 ↗','/static/bruce.html',true)}${button('返回我的角色','#/mine')}</div><div class="settings">${[['共同记忆','未来承接经过确认的共同经历与关系节点。当前手动记忆可在对话页查看。'],['日记与动态','角色生活事件尚未接入，暂时没有动态。'],['相册','未来放置你上传或获授权的角色图像，当前没有照片。'],['空间外观','主题和视觉资产的设置位置已预留，后续开放。']].map(([a,b])=>`<div class="panel"><h3>${a}</h3><p class="muted">${b}</p></div>`).join('')}</div>`;}
let editingId=null;
function studio(id){const d=state.drafts.find(d=>d.id===id)||{};editingId=d.id||null;return `${head('CREATOR STUDIO / 创作中心','让一个想法，成为一个角色。','先写下他是谁，再慢慢补全他的世界。草稿默认私有，不会自动公开，也不会改变 Bruce 的设定。')}<div class="steps"><span>01 基本身份</span><span>02 性格与表达</span><span>03 世界与关系</span><span>04 开场与预览</span></div><div class="studio"><form id="creator-form" class="panel"><div class="form-grid">${[['name','角色名字','例如：林间',80],['identity','身份与一句话介绍','例如：不愿关店的旧书店老板',160],['personality','性格与表达','他如何说话？喜欢什么？有什么边界？',1500],['world','世界与背景','他住在哪里？经历过什么？',1500],['relationship','初始关系','例如：第一次见面的旅人',300],['opening','第一句开场','如果此刻遇见你，他会说什么？',500]].map(([key,label,placeholder,max])=>`<label class="${['personality','world','opening'].includes(key)?'wide':''}">${label}${['personality','world','opening'].includes(key)?`<textarea name="${key}" maxlength="${max}" placeholder="${placeholder}">${esc(d[key])}</textarea>`:`<input name="${key}" maxlength="${max}" ${key==='name'?'required':''} placeholder="${placeholder}" value="${esc(d[key])}">`}</label>`).join('')}</div><div class="notice">本轮只保存角色草稿，尚未接入角色生成与试聊。公开发布、授权与结算将后续开放。</div><div class="actions"><button class="button primary" type="submit">保存私有草稿</button><button class="button" type="button" data-unavailable="创作者发布功能尚未开放；保存草稿不会公开角色。">发布 · 尚未开放</button></div><p id="save-status" class="muted" role="status">仅存此浏览器，可在个人中心导出备份。</p></form><aside class="preview"><div class="eyebrow">LIVE PREVIEW / 档案预览</div><div id="draft-preview" class="panel" style="margin-top:18px"></div><p class="muted">形象暂用文字占位。以后可替换立绘、表情和动态素材。</p></aside></div>`;}
function preview(){const d=Object.fromEntries(new FormData($('#creator-form')));$('#draft-preview').innerHTML=`${portrait({name:d.name||'?',initial:(d.name||'?').slice(0,1)})}<div class="card-body"><span class="tag">私有草稿</span><h2>${esc(d.name||'尚未命名的角色')}</h2><p class="muted">${esc(d.identity||'他的身份，由你来定义。')}</p><p>“${esc(d.opening||'故事的第一句话，留给你。')}”</p><small>${esc(d.relationship||'初始关系待填写')}</small></div>`;}
function account(){return `${head('SETTINGS / 个人中心','为你的故事，留好边界。','当前以访客体验平台。团队访问码用于 Bruce 试聊，不等同于个人账号。')}<div class="settings"><div class="panel"><h3>账号与身份</h3><p class="muted">个人注册、登录和跨设备同步尚未接入。同一浏览器中的使用者会共用本地数据。</p><button class="button" data-unavailable="个人账号系统尚未开放。Bruce 的团队访问码在进入对话时输入。">账号功能 · 待开放</button></div><div class="panel"><h3>订阅与订单</h3><p class="muted">当前没有收费套餐，也不会产生订单。未来会在这里管理订阅、购买和授权。</p><span class="tag">未接入支付</span></div><div class="panel"><h3>本地收藏与草稿</h3><p class="muted">已收藏 ${state.favorites.length} 位角色，保存 ${state.drafts.length} 份草稿。清除浏览器数据会丢失这些内容。</p><div class="actions"><button class="button" id="export-data">导出备份</button><button class="text-link" id="clear-platform">清除平台本地数据</button></div><small>此操作不清除 Bruce 的聊天与记忆。</small></div><div class="panel"><h3>对话、记忆与向导</h3><p class="muted">Bruce 的聊天与手动记忆在对话页中分别查看和清除。看板娘当前仅使用固定台词，不读取你的聊天。</p><div class="actions">${button('管理 Bruce 对话','/static/bruce.html')}<button class="text-link" id="show-guide">显示接待员</button></div></div></div>`;}
function missing(){return empty('这条裂缝还没有连接','页面或角色不存在，你可以回到接待站。','返回接待站','#/home');}
let formDirty=false;
function render(){const [path,query='']=(location.hash.slice(1)||'/home').split('?');const parts=path.split('/').filter(Boolean), page=parts[0],id=parts[1];const params=new URLSearchParams(query);const views={home:()=>home(),explore:()=>explore(params),character:()=>detail(characters.find(c=>c.id===id)),mine:()=>mine(params.get('tab')||'recent'),studio:()=>studio(id),space:()=>id==='bruce'?space():missing(),account};document.body.dataset.scene=({home:'home',explore:'explore',character:'explore',mine:'space',space:'space',studio:'studio',account:'quiet'})[page]||'quiet';$('#main').innerHTML=(views[page]||missing)();document.querySelectorAll('.header nav a').forEach(a=>{const active=a.hash===`#/${page}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=`${({home:'接待站',explore:'角色广场',character:'角色档案',mine:'我的角色',studio:'创作中心',space:'私人空间',account:'个人中心'})[page]||'未找到'} · 间隙 Interspace`;if(page==='explore'){$('#source').value=['official','creator'].includes(params.get('source'))?params.get('source'):'all';$('#theme').value=['night','companion'].includes(params.get('theme'))?params.get('theme'):'all';filterResults();$('#search').addEventListener('input',filterResults);$('#source').addEventListener('change',filterResults);$('#theme').addEventListener('change',filterResults);}if(page==='studio'){preview();$('#creator-form').addEventListener('input',()=>{formDirty=true;preview();$('#save-status').textContent='有未保存的修改';});$('#creator-form').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.name.trim()){toast('请填写角色名字');return;}d.name=d.name.trim();d.id=editingId||crypto.randomUUID();const i=state.drafts.findIndex(x=>x.id===d.id);if(i<0)state.drafts.push(d);else state.drafts[i]=d;editingId=d.id;if(persist()){formDirty=false;$('#save-status').textContent='已保存到当前浏览器 · 私有';history.replaceState(null,'',`#/studio/${d.id}`);toast('私有草稿已保存');}});}formDirty=false;$('#guide-panel').hidden=true;$('#guide-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);}
function showModal(html){$('#modal-body').innerHTML=html;$('#modal').showModal();}
let lastEncounter=null;
document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.matches('a[href^="#/"]')&&formDirty&&!confirm('草稿有未保存的修改，确定离开吗？')){e.preventDefault();return;}if(t.hasAttribute('data-favorite')){const id=t.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];persist();const y=scrollY;render();scrollTo(0,y);}if(t.hasAttribute('data-encounter')){const pool=characters.filter(c=>c.id!==lastEncounter);const c=pool[Math.floor(Math.random()*pool.length)];lastEncounter=c.id;showModal(`<div class="eyebrow">AN UNEXPECTED MEETING</div><h2>这一次，遇见 ${c.name}。</h2>${portrait(c)}<p style="margin-top:20px">“${c.quote}”</p><p class="muted">${c.live?'可以进入真实试聊。':'概念角色 · 当前仅能浏览档案。'}</p><div class="actions">${button('查看角色档案 ↗',`#/character/${c.id}`,true)}<button class="button" data-encounter>换一个</button></div>`);}if(t.closest('#modal')&&t.matches('a'))$('#modal').close();if(t.hasAttribute('data-unavailable'))toast(t.dataset.unavailable);if(t.dataset.mine)location.hash=`/mine?tab=${t.dataset.mine}`;if(t.dataset.delete){if(confirm('删除这份本地草稿？此操作不能撤销。')){state.drafts=state.drafts.filter(d=>d.id!==t.dataset.delete);persist();render();}}if(t.id==='export-data'){const blob=new Blob([JSON.stringify({version:1,favorites:state.favorites,drafts:state.drafts},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='interspace-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(t.id==='clear-platform'&&confirm('清除本浏览器的平台收藏、草稿和向导偏好？Bruce 聊天不受影响。')){state={favorites:[],drafts:[],guideHidden:false};persist();render();syncGuide();}if(t.id==='show-guide'){state.guideHidden=false;persist();syncGuide();toast('接待员已显示');}});
const lines=['欢迎来到间隙。这里暂时只有一位能聊天的来访者：Bruce。要去认识一下吗？','不知道从谁开始？试试“随机相遇”。概念角色可以先看看设定。','角色草稿默认只保存在你的浏览器里。写了很久的故事，记得导出备份。','接待站守则第一条：允许迷路。第二条：左上角永远可以回家。'];let line=0;
function syncGuide(){$('.guide').hidden=state.guideHidden;$('#guide-restore').hidden=!state.guideHidden;}
$('#guide-toggle').onclick=()=>{const open=$('#guide-panel').hidden;$('#guide-panel').hidden=!open;$('#guide-toggle').setAttribute('aria-expanded',String(open));$('#guide-text').textContent=lines[line];};$('#guide-next').onclick=()=>{$('#guide-text').textContent=lines[++line%lines.length];};$('#guide-close').onclick=()=>{$('#guide-panel').hidden=true;$('#guide-toggle').setAttribute('aria-expanded','false');};$('#guide-hide').onclick=()=>{state.guideHidden=true;persist();syncGuide();};$('#guide-restore').onclick=()=>{state.guideHidden=false;persist();syncGuide();};$('.modal-close').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close();});window.addEventListener('hashchange',render);window.addEventListener('beforeunload',e=>{if(formDirty){e.preventDefault();e.returnValue='';}});render();syncGuide();
})();
